---
title: "Inicio"
author: "Lucas Arteaga"
date: "29-11-2021"
output: html_document

bibliography: Input/bib/citations.bib
csl: Input/bib/apa.csl
link-citations: yes
---
## Resumen

Para el desarrollo de políticas públicas orientadas a mejorar la calidad educativa en Chile, se utilizan herramientas encargadas de medir aspectos como el rendimiento académico de los establecimientos educacionales a lo largo del país. Diversas investigaciones han demostrado la variedad de factores que inciden, ya sea negativa o positivamente, en los resultados obtenidos por los alumnos. Esta investigación tiene como objetivo determinar el efecto que las variables de: Autoestima académica y motivación escolar; Hábitos saludables y; Grupo Socioeconómico al que pertenece el establecimiento, tienen sobre el rendimiento académico. 

Para ello, se utilizó la base de datos SIMCE de segundo año de enseñanza media, edición 2018, la cual cuenta con 2925 casos -luego de filtrar casos perdidos- y 76 variables, de las cuales se seleccionó una variable dependiente: promedio de puntajes respecto de la media alcanzada por establecimiento para cada prueba, y 3 independientes: Puntaje de Autoestima académica, Puntaje de Hábitos de vida saludable y Nivel socioeconómico del establecimiento (GSE). 

El problema de investigación reside en si existe una relación entre la autoestima académica y los hábitos saludables, y si estos inciden en los puntajes de lectura, matemáticas y ciencias naturales del SIMCE 2018 de segundos medios, siendo el objetivo y argumento central que la autoestima académica y hábitos saludables inciden en los puntajes. 

Respecto a los resultados obtenidos, se determina que, si bien las tres variables presentan una relación positiva en función al puntaje obtenido, hábitos de vida saludable y autoestima académica presentan menos influencia en comparación con el grupo socioeconómico (GSE), el cual resulta ser determinante a la hora de explicar el desempeño académico de los establecimientos. De acuerdo con la correlación positiva que se obtiene entre las variables, se evidencia a favor de las hipótesis propuestas inicialmente.